// Generates the static world map used by the "Rota Traçada" landing.
// Source: Natural Earth 1:110m via world-atlas (public domain).
// Output:
//   public/map/land.svg, public/map/graticule.svg  (static, cached; tinted via CSS mask-image)
//   src/components/map/world-map-data.ts           (highlighted countries + cities, inlined)
// Usage: node scripts/build-map.mjs
import { mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoEqualEarth, geoGraticule, geoPath } from "d3-geo";
import { feature, merge } from "topojson-client";

const require = createRequire(import.meta.url);
const world = require("world-atlas/countries-110m.json");

const WIDTH = 1600;
// Centered at 30°E so Brazil sits left, Canada top-left and Oceania on the right.
const projection = geoEqualEarth().rotate([-30, 0]);

const countries = feature(world, world.objects.countries);
// Drop Antarctica: it eats vertical space and adds nothing to the story.
const kept = countries.features.filter((f) => f.id !== "010");
projection.fitWidth(WIDTH, { type: "FeatureCollection", features: kept });

const path = geoPath(projection).digits(0);
const [[, y0], [, y1]] = path.bounds({ type: "FeatureCollection", features: kept });
const HEIGHT = Math.ceil(y1 - y0 + 20);
projection.translate([projection.translate()[0], projection.translate()[1] - y0 + 10]);

/** Integer coordinates are sub-pixel at 1600 wide and keep the payload small. */
const round = (d) => d ?? "";

const HIGHLIGHT = { BR: "076", AU: "036", NZ: "554", CA: "124" };
const highlightIds = new Set(Object.values(HIGHLIGHT));

const landGeometries = world.objects.countries.geometries.filter(
  (g) => g.id !== "010" && !highlightIds.has(g.id),
);
const land = round(path(merge(world, landGeometries)));

const countryPaths = {};
const countryBounds = {};
for (const [code, id] of Object.entries(HIGHLIGHT)) {
  const f = countries.features.find((c) => c.id === id);
  countryPaths[code] = round(path(f));
  const [[x0b, y0b], [x1b, y1b]] = path.bounds(f);
  countryBounds[code] = [x0b, y0b, x1b - x0b, y1b - y0b].map((n) => Math.round(n));
}

const graticule = round(path(geoGraticule().step([20, 20]).precision(5)()));

// Capitals (lon, lat): the route goes from government to government.
const CITIES = {
  brasilia: { label: "Brasília", coords: [-47.88, -15.79] },
  canberra: { label: "Canberra", coords: [149.13, -35.28] },
  wellington: { label: "Wellington", coords: [174.78, -41.29] },
  ottawa: { label: "Ottawa", coords: [-75.7, 45.42] },
};
const cities = Object.fromEntries(
  Object.entries(CITIES).map(([key, c]) => {
    const [x, y] = projection(c.coords);
    return [
      key,
      {
        label: c.label,
        lon: c.coords[0],
        lat: c.coords[1],
        x: Math.round(x * 10) / 10,
        y: Math.round(y * 10) / 10,
      },
    ];
  }),
);

const out = `// AUTO-GENERATED by scripts/build-map.mjs. Do not edit by hand.
// Natural Earth 1:110m (public domain), Equal Earth projection centered at 30°E.

export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};

export const countryPaths = ${JSON.stringify(countryPaths, null, 2)} as const;

/** [x, y, width, height] in map units. */
export const countryBounds = ${JSON.stringify(countryBounds, null, 2)} as const;

export const cities = ${JSON.stringify(cities, null, 2)} as const;
`;

mkdirSync("public/map", { recursive: true });
const svg = (body) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${HEIGHT}">${body}</svg>`;
writeFileSync("public/map/land.svg", svg(`<path fill="#000" d="${land}"/>`));
writeFileSync(
  "public/map/graticule.svg",
  svg(
    `<path fill="none" stroke="#000" stroke-width="1" vector-effect="non-scaling-stroke" d="${graticule}"/>`,
  ),
);
writeFileSync("src/components/map/world-map-data.ts", out);
console.log(`map ${WIDTH}x${HEIGHT}, ${(out.length / 1024).toFixed(1)} KB`);
